[package]
name = "grpr"
version = "0.1.0"
edition = "2021"
description = "A CLI tool to recursively execute Git commands in subdirectories that are Git repositories."
license = "MIT"
repository = "https://github.com/evolve75/grpr"

[dependencies]
walkdir = "2.4.3"
